backend:
  name: git-gateway
  branch: master

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "public/okladki" # Media files will be stored in the repo under images/uploads
public_folder: "" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "publikacje" # Used in routes, e.g., /admin/collections/blog
    label: "Publikacje" # Used in the UI
    folder: "src/pages/publikacje" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/PubLayout.astro"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Year", name: "pubYear", widget: "number"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Image big", name: "imageBig", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}